### PR TITLE
added JTAG2SWD sequence, connects under RESET as ST-LINKV 2

### PR DESCRIPTION
**Pull request by FMode**
a timeout needs to be added

### CODE REVIEW

**Comment by Murakhovskyi** [comment]
Has anything changed regarding the connection? We connect RESET_Pin 27(NRST PIN 7 on LQFP64)
PWR_Pin 26
SWDIO_Pin 14
SWCLK_Pin 15
GND is not needed?
Sorry for the banal questions, I’m working on something a little different, but in general, I need to backup Flash and transfer it to another one of the same kind.
I am working with STM32F030CC

**Comment by Murakhovskyi** [comment]
Your option gets stuck on Send anything to start...
Send anything to start...
Send anything to start...
Starting

MCU STM32F030CCT6

**Comment by FMode** [comment]
GND is needed anytime. I did not change pins (please look into code). But I change RESET from Output to Input because my target resets in a loop. I am waiting unlimited for the reset state. As written as TODO: a wait timeout (1-5 sec?) should be implemented. So if not needed comment out the waiting. A development/build environment is needed anyway because you need to adapt the memory addresses for your needs.

**Comment by Murakhovskyi** [comment]
> GND is needed anytime. I did not change pins (please look into code). But I change RESET from Output to Input because my target resets in a loop. I am waiting unlimited for the reset state. As written as TODO: a wait timeout (1-5 sec?) should be implemented. So if not needed comment out the waiting. A development/build environment is needed anyway because you need to adapt the memory addresses for your needs.



> GND is needed anytime. I did not change pins (please look into code). But I change RESET from Output to Input because my target resets in a loop. I am waiting unlimited for the reset state. As written as TODO: a wait timeout (1-5 sec?) should be implemented. So if not needed comment out the waiting. A development/build environment is needed anyway because you need to adapt the memory addresses for your needs.

Good afternoon, in order to eliminate any factors that could interfere, I desoldered the chip (STM32F091) and soldered it directly to the LQFP64 legs:
64.VDD - 26 Pin PWR Pico
18.VSS - 28 Pin GND Pico
7.NRST - 27 Pin RESET Pico
46.PA13(SWDIO) - 14 Pin SWDIO Pico
49.PA14(SWCLK) - 15 Pin SWCLK Pico

In the original version of racerxdl, I have error 244 (E0), in your version, it just freezes after Starting.
I need this whole idea to resurrect the device whose MCU burned out.

Tell me what I'm doing wrong. I'll be very grateful.

**Comment by FMode** [comment]
> Good afternoon, in order to eliminate any factors that could interfere, I desoldered the chip (STM32F091) and soldered it directly to the LQFP64 legs: 64.VDD - 26 Pin PWR Pico 18.VSS - 28 Pin GND Pico 7.NRST - 27 Pin RESET Pico 46.PA13(SWDIO) - 14 Pin SWDIO Pico 49.PA14(SWCLK) - 15 Pin SWCLK Pico
> 
> In the original version of racerxdl, I have error 244 (E0), in your version, it just freezes after Starting. I need this whole idea to resurrect the device whose MCU burned out.
> 
> Tell me what I'm doing wrong. I'll be very grateful.

It seems your cpu is not resetting... 
Just disable my waiting for a reset. (2 while loops) 
```
while(digitalRead(TARGET_RESET_Pin) != LOW){};  
while(digitalRead(TARGET_RESET_Pin) == LOW){};

```
The JTAG2SWD command does not harm you it only makes you a bit slower if you really dont need it.
I removed the driving of the RESET line to high because this can "pseudo-power" a device.

**Pull request closed without merging**
